### ISSUE TITLE
Add: Toasts for users awaiting verification

### ISSUE THREAD

**Issue by samuel-ma** [samuel-ma/Gesa#14]

**Comment by thisisairo** [comment]
## Subject: [Issue #14] Adding Toasts for Users Awaiting Verification

Hello everyone,

I hope you're doing well. I noticed the issue titled **"Add: Toasts for users awaiting verification"** and I would like to contribute to resolving this matter.

### Background

From what I understand, the issue is about implementing toast messages to improve the user experience for those awaiting verification. Toast messages are a great way to provide unobtrusive feedback to users, and it will undoubtedly enhance the verification process for new members.

### Proposed Plan

I would like to take on this task and start working on it. Before I begin, I would like to gather some more information and discuss the following points:

1. **Design Guidelines**: Could someone please provide design guidelines or preferences for the toast messages? This will ensure that the toasts align with the project's overall visual style.

2. **Timing and Triggers**: When should these toast messages appear? Should they trigger on specific events, such as after a user submits their verification request, or when they navigate to a certain page?

3. **Toast Duration**: What is the ideal duration for displaying the toast messages? Should they automatically disappear after a few seconds, or should users manually close them?

### Contribution

I am excited to contribute and make Gesa an even better platform for students. I will keep the community updated on my progress regularly and maintain open communication to address any feedback or suggestions during the implementation process.

Looking forward to collaborating with the team and fellow contributors!

Best regards,

[MMW](https://github.com/Mohsin-mw)
GitHub username: @Mohsin-mw

**Comment by samuel-ma** [comment]
@Mohsin-mw 
I just came across your response to this issue 
You sound very enthusiastic 
I bet your a great developer
Thanks for reaching out and trying to contribute to this repo
Unfortunately....it's been deprecated and no longer being worked on

If you don't mind though, we can work a project in the near future
Am looking to work side by side with an experienced backend dev on an interesting community project soon
Thanks alot again....
And best regards,

[Samuel ma](github.com/samuel-ma)

**Comment by samuel-ma** [comment]
@Mohsin-mw 
I just came across your response to this issue 
You sound very enthusiastic 
I bet your a great developer
Thanks for reaching out and trying to contribute to this repo
Unfortunately....it's been deprecated and no longer being worked on

If you don't mind though, we can work a project in the near future
Am looking to work side by side with an experienced backend dev on an interesting community project soon
Thanks alot again....
And best regards,

[Samuel ma](github.com/samuel-ma)
